default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy yelpfusion
        language: system
        # run on all files
        pass_filenames: false
        types: [python]
      - id: test
        name: test
        entry: poetry run pytest
        language: system
        # run on all files
        pass_filenames: false
        types: [python]
